env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:json/recommended
plugins:
  - jest
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    alias:
      - ['~', './']
      - ['@@', './src']
      - ['@config', './src/config']
      - ['@controllers', './src/controllers']
      - ['@models', './src/models']
      - ['@repositories', './src/repositories']
      - ['@routes', './src/routes']
      - ['@utils', './src/utils']
rules: {}
