git: false
github:
  release: true
  releaseNotes: generate-release-notes.sh --from=${latestTag} --to=${tagName}
plugins:
  '@release-it/conventional-changelog':
    preset: angular
    infile: CHANGELOG.md
npm:
  publish: false

